// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEUIPWh3NGS2rdmEEFio4aW7xIRYDrwHM',
    appId: '1:956483007320:web:d5216bcb7b95c23369eb2d',
    messagingSenderId: '956483007320',
    projectId: 'student-hub-1354c',
    authDomain: 'student-hub-1354c.firebaseapp.com',
    storageBucket: 'student-hub-1354c.firebasestorage.app',
    measurementId: 'G-WJC8ERYGZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv3E9YgMGi9tpB7hb6vIwNe20NHFJuHew',
    appId: '1:956483007320:android:61a14fb698c694dd69eb2d',
    messagingSenderId: '956483007320',
    projectId: 'student-hub-1354c',
    storageBucket: 'student-hub-1354c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyhWB3WgbD3GBwTtKeGSc97RSqxSEaJ24',
    appId: '1:956483007320:ios:d9681412cb67a10d69eb2d',
    messagingSenderId: '956483007320',
    projectId: 'student-hub-1354c',
    storageBucket: 'student-hub-1354c.firebasestorage.app',
    iosBundleId: 'com.example.studentCommunityHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyhWB3WgbD3GBwTtKeGSc97RSqxSEaJ24',
    appId: '1:956483007320:ios:d9681412cb67a10d69eb2d',
    messagingSenderId: '956483007320',
    projectId: 'student-hub-1354c',
    storageBucket: 'student-hub-1354c.firebasestorage.app',
    iosBundleId: 'com.example.studentCommunityHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEUIPWh3NGS2rdmEEFio4aW7xIRYDrwHM',
    appId: '1:956483007320:web:e345bab4b2e78d6a69eb2d',
    messagingSenderId: '956483007320',
    projectId: 'student-hub-1354c',
    authDomain: 'student-hub-1354c.firebaseapp.com',
    storageBucket: 'student-hub-1354c.firebasestorage.app',
    measurementId: 'G-DCMD4M8XBC',
  );
}
